### PR TITLE
Fix cannon loading

### PR DESCRIPTION
**Pull request by PainOchoco**
There was an issue with the loading of the cannon:
The regex matching coordinates was only matching positive integers (like "1,2,3").
Now it's matching signed floats (like "-44.844574,-4.932205,-165.382137").
There was also a typo on the split limit and the logger name.

It's now loading fine and adding all the coordinates to the cannon tree.
Please give me feedback!

### CODE REVIEW

**Comment by PainOchoco** [comment]
Also the regex matching is taking a lot of times, it takes ~10 seconds on my computer and on the main client thread so it freeze the game during that time.

We could try to decrease the time taken by the regex matching or load the cannon in a secondary thread.

**Comment by kikugie** [comment]
Thanks for the PR and the suggestions! I've removed regex checks entirely and replaced it with error handling.   
There's also the proposed async loading, although in a shitty way. I'm going to revisit it later, but if you have ideas, feel free to push.

**Comment by PainOchoco** [comment]
Does the loading takes significant time without regex now? If not I don't think that an async loading is really needed

**Comment by kikugie** [comment]
After checking both implementations (with cubic's anvil cannon and my mid laptop), no regex implementation has an overhead of a whole **0.4 seconds**.  
But because the current implementation dispatches a new thread for each load task, it adds a second of overhead (non-blocking, however). This is fixed with creating a static thread and assigning loading tasks to it.

**Pull request merged**
